/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Model.character.Golem;
import org.example.Model.character.Hero;
import org.example.controller.MyController;
import org.example.view.MyView;

public class App {

    // This method initializes the view and controller, and sets up the relationships between them.
    public MyView init() {
        MyView view = new MyView();
        MyController controller = new MyController(new Golem(), new Hero("Arthur", 50, "Dragrice"));

        view.setController(controller);
        controller.setView(view);

        return view;
    }
    
    public static void main(String[] args) {
        App app = new App();
        MyView view = app.init();

        view.init();

        view.theHeroEquipsSword();
        view.theHeroAttacks();
        view.endTurn();

        view.theHeroAttacks();
        view.endTurn();
        
        view.theHeroEquipsHaxe();
        view.theHeroAttacks();
    }
}
