org.example.Model.character.Hero#equipWeapon(Lorg/example/Model/weapon/Weapon;)V=14
org.example.Model.character.Hero#getWeapon()Lorg/example/Model/weapon/Weapon;=13
org.example.Model.character.Hero#getName()Ljava/lang/String;=15
org.example.controller.MyController#setHero()V=3
org.example.Model.character.Golem#getName()Ljava/lang/String;=8
org.example.Model.weapon.Weapon#getDamage()I=16
org.example.Model.character.Monster#takeDamage(I)V=10
org.example.App#sendMessage(Ljava/lang/String;)V=1
org.example.controller.MyController#newHero()Lorg/example/Model/character/Hero;=4
org.example.App#main([Ljava/lang/String;)V=2
org.example.controller.MyController#theHeroAttacks()V=6
org.example.Model.character.Golem#takeDamage()V=9
org.example.Model.weapon.Weapon#getName()Ljava/lang/String;=17
org.example.Model.character.Character#getHealth()I=11
org.example.App#init()Lorg/example/controller/MyController;=0
org.example.controller.MyController#theHeroEquipsSword()V=5
org.example.controller.MyController#getHeroName()Ljava/lang/String;=7
org.example.Model.character.Character#getName()Ljava/lang/String;=12
