org.example.Model.character.Hero#<init>(Ljava/lang/String;ILjava/lang/String;)V=18
org.example.Model.character.Hero#getWeapon()Lorg/example/Model/weapon/Weapon;=19
org.example.Model.character.Golem#getName()Ljava/lang/String;=11
org.example.Model.weapon.Weapon#getDamage()I=23
org.example.App#main([Ljava/lang/String;)V=3
org.example.controller.MyController#theHeroAttacks()V=8
org.example.Model.character.Golem#takeDamage()V=12
org.example.Model.weapon.Weapon#getName()Ljava/lang/String;=24
org.example.Model.character.Golem#<init>()V=10
org.example.Model.character.Character#getHealth()I=16
org.example.App#init()Lorg/example/controller/MyController;=1
org.example.Model.character.Hero#equipWeapon(Lorg/example/Model/weapon/Weapon;)V=20
org.example.Model.character.Hero#getName()Ljava/lang/String;=21
org.example.Model.character.Monster#<init>(Ljava/lang/String;I)V=13
org.example.controller.MyController#setHero()V=5
org.example.App#<init>()V=0
org.example.App#sendMessage(Ljava/lang/String;)V=2
org.example.Model.character.Monster#takeDamage(I)V=14
org.example.controller.MyController#newHero()Lorg/example/Model/character/Hero;=6
org.example.Model.weapon.Weapon#<init>(Ljava/lang/String;I)V=22
org.example.Model.character.Character#<init>(Ljava/lang/String;I)V=15
org.example.controller.MyController#<init>(Lorg/example/Model/character/Golem;)V=4
org.example.controller.MyController#theHeroEquipsSword()V=7
org.example.controller.MyController#getHeroName()Ljava/lang/String;=9
org.example.Model.character.Character#getName()Ljava/lang/String;=17
